import Head from 'next/head'
import React from 'react'
import styles from '../styles/Home.module.css'
import { useAccount, useConnect, useDisconnect, useContract, useSigner } from 'wagmi'
// import { calculatorAbi } from '../src/abi'
import { useToast, Button, Input, Text, Flex, Box, Heading, NumberInput, NumberInputField, Drawer, DrawerContent, DrawerHeader, DrawerBody, useColorMode } from '@chakra-ui/react'
import { abi, address as contractAddress } from '../src/constants'
import { NFTGrid } from '../src/components'
import { SquareNFT } from '../src/types'
import NftView from '../src/components/NftView'
import { formatString } from '../src/utils'

const GRID_HEIGHT = 25;
const GRID_WIDTH = 40;

export default function Home() {

  // Wagmi
  // const { address, isConnected } = useAccount()
  const { address, isConnected } = { isConnected: true, address: 'x' }
  const { data: signer } = useSigner()
  const { connect, connectors } = useConnect()
  const { disconnect } = useDisconnect()

  // Contract metadata
  const contract = useContract({ address: contractAddress, abi, signerOrProvider: signer })
  const [contractName, setContractName] = React.useState<string>()
  const [contractSymbol, setContractSymbol] = React.useState<string>()
  const [cells, setCells] = React.useState<SquareNFT[][]>([[]])

  // ui
  const { toggleColorMode } = useColorMode()
  const [selectedCell, setSelectedCell] = React.useState<SquareNFT>()
  const toast = useToast()

  React.useEffect(() => {
    // Getting from the contract.
    const newCells = Array(1000).fill('').map((_e, ind) => ({
      tokenId: ind
    }) as SquareNFT)

    const newCellsReshaped = []
    while (newCells.length) newCellsReshaped.push(newCells.splice(0, GRID_WIDTH));
    setCells(newCellsReshaped)
  }, [])

  React.useEffect(() => {
    const updateContractDetails = async () => {
      if (contract && isConnected) {
        const promises = [contract.name(), contract.symbol()]
        const promisesResult = await Promise.allSettled(promises)
        if (promisesResult[0].status === 'fulfilled') {
          setContractName(promisesResult[0].value)
        }
        if (promisesResult[1].status === 'fulfilled') {
          setContractSymbol(promisesResult[1].value)
        }
      }
    }
    updateContractDetails()
  }, [contract, isConnected])

  React.useEffect(() => {
    toggleColorMode()
    disconnect()
  }, [])

  const handleOnClickCell = (cell: SquareNFT) => {
    setSelectedCell(cell)
  }

  const buyNft = async (nft: SquareNFT, title: string, image: string) => {
    try {
      const promise = new Promise((resolve, reject) => {
        setTimeout(() => {
          reject("foo");
        }, 300);
      })
      await promise
      toast({
        title: `NFT bought!`,
        description: `You've successfully purchased the NFT number ${nft.tokenId}.`,
        status: 'success',
        duration: 3000,
        isClosable: true,
      })
    }
    catch (e) {
      let result = 'unknow';
      if (typeof e === "string") {
        result = e 
      } else if (e instanceof Error) {
        result = e.message 
      }
      toast({
        title: `NFT purchase failed!`,
        description: `You couldn't purchased the NFT number ${nft.tokenId}. ${formatString(result)}.`,
        status: 'error',
        duration: 3000,
        isClosable: true,
      })
    }


  }

  return (
    <Box p="0 2rem">
      <Head>
        <title>ERC20 Contract</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        {isConnected ?
          <React.Fragment>
            <Heading as='h1' fontSize={"4rem"} lineHeight="1.1">
              Welcome to <span className={styles.blue}>Blockchain SU-Squares Contract</span>
            </Heading>

            <Heading mt='10'>
              The address of the contract is <span className={styles.blue}>{contractAddress}</span>
            </Heading>

            <Text mt='10'>
              The name of the contract is <span className={styles.blue}>{contractName}</span>
              <br />
              The symbol of the contract is <span className={styles.blue}>{contractSymbol}</span>
              <br />
            </Text>

            <Heading mt='10' mb="10">
              Your address: <span className={styles.blue}>{address}</span>
            </Heading>
            <Flex flexDir={'row'} w='100%' gap={3} >
              <NFTGrid w='80%' onClickCell={handleOnClickCell} cells={cells} selected={selectedCell} />

              <NftView w='20%' nftMetadata={selectedCell} buyNft={buyNft} />
            </Flex>

          </React.Fragment>
          :
          <React.Fragment>
            <Heading fontSize={"4rem"} lineHeight="1.1">
              Welcome to <span className={styles.blue}>Blockchain ERC20 Contract</span>
            </Heading>
            <Text >
              Please connect to metamask to continue.
            </Text>
            <div className={styles.inputs}>
              <Button onClick={() => {
                connect({ connector: connectors[0] })
              }}>Connect Wallet</Button>
            </div>
          </React.Fragment>
        }
      </main>
    </Box>
  )
}
